### ISSUE TITLE
Offene Frage der Verbindlichkeit

### ISSUE THREAD

**Issue by HelenBielawa** [stadt-bielefeld/izud#1]
Ich würde mir wünschen, dass in der Einleitung erklärt wird, ob/wie verbindlich die Leitlinien sind. Das Wort "Leitlinien" suggeriert meiner Meinung nach eine Verbindlichkeit. Allerdings besteht diese ja nicht - außer der Rat beschließt sie künftig. Trotzdem steht dort, dass die Stadt bei ihren Beteiligungen auf eine Einhaltung hinwirkt...wird sie das wirklich tun? Entweder, alles wird als Aufforderung/Wunsch formuliert, oder es wird oben klar gemacht, dass diese Vereinbarung ein Zielbild ist, dem sich aber leider bisher niemand verpflichtet hat.

**Comment by Duragtan** [comment]
Ja, einer unserer Forschenden wünschte sich so etwas wie einen "Automatismus" zur Veröffentlichung bestimmter Daten. Für die Forschung werden Daten eben interessanter je länger die Zeiträume sind, die sie beleuchten und wenn die Daten regelmäßig veröffentlicht werden. Da wäre eine Verbindlichkeit zumindest in manchen Bereichen ein starkes Argument, das Forschende dazu motivieren wird, auch mit diesen Daten zu arbeiten.

**Comment by Duragtan** [comment]
Ähnlich hat sich der selbe Forschende dafür ausgesprochen in Abschnitt 5. für folgende Streichung ausgesprochen

> Hervorgehende Projekte werden -nach Möglichkeit- transparent kommuniziert.

**Comment by Duragtan** [comment]
Ebenso für stärkere Formulierungen in Abschnitt 7. "Selbstverpflichtung"

**Comment by buprak** [comment]
Die Rückmeldungen wurden in der Überarbeitung entsprechend übernommen und können in der neuen Version nachgelesen werden.

**Comment by buprak** [comment]
Die Rückmeldungen wurden in der Überarbeitung entsprechend übernommen und können in der neuen Version nachgelesen werden.

**Comment by buprak** [comment]
Die Rückmeldungen wurden in der Überarbeitung entsprechend übernommen und können in der neuen Version nachgelesen werden.
