### ISSUE TITLE
Verkauf oder kein Verkauf

### ISSUE THREAD

**Issue by Duragtan** [stadt-bielefeld/izud#10]
Unabhängig von unserer Diskussion zu diesem Thema am vergangenen Dienstag: Abschnitt "2. Datenschutz" scheint in sich widersprüchlich: Am Anfang des zweiten Absatzes heißt es:

> Bei der Erhebung, Speicherung, Verarbeitung, Zusammenführung mit anderen Daten, Weitergabe, **Verkauf**, Auswertung, Kategorisierung und Veröffentlichung von Daten ...

Am Ende des selben Absatz heißt es:

> Die Erfassung und gegebenenfalls Weitergabe von personenbezogenen Daten geschehen nicht zum Zwecke eines **Verkaufs** oder Erlangung einer geldwerten Leistung.

**Comment by buprak** [comment]
Die Rückmeldung haben wir im Entwurf mit aufgenommen und entsprechen überarbeitet. Das kann in der neuen Version nachgelesen werden.
