### ISSUE TITLE
Was macht einen guten Datensatz aus? (aus Sicht der Wissenschaft)

### ISSUE THREAD

**Issue by Duragtan** [stadt-bielefeld/izud#12]
* Die Daten decken einen langen Zeitraum ab.
* Der Datensatz enthält möglichst viele Informationen/Variablen (Spalten).
* Der Datensatz ist durch Metadaten ausführlich kommentiert. Darunter
** Umfassende Angaben dazu, wie die Daten erhoben wurden
** Bedeutung der Variablen/Spalten
** Bedeutung von Null-Werten und fehlenden Werten
** Spalten, die als Querverweise zu anderen Datensätzen dienen
** ... tbc
* Der Datensatz hat ein nachvollziehbares, regelmäßiges Update-Intervall

**Comment by Duragtan** [comment]
Ein*e Prof*in der Uni schlug gar ein Peer-Review von Datensätzen vor, evtl. auch durch Prof*innen der Uni. Ich bin nicht wirklich sicher, wie viele Prof*innen dazu bereit wären, aber mindestens eine*r.

**Comment by buprak** [comment]
Vielen Dank für die ganzen guten Hinweise. Diese Überlegungen haben wir derzeit auch intern und berücksichtigen diese bei internen Strategien zur Veröffentlichung von Verwaltungsdaten. Zu überlegen wäre sowas auch öffentlich aufzubereiten als eine Art Leitfaden.

Dazu können wir gerne nochmal sprechen! Für unseren Entwurf zum Umgang mit Daten in der Stadt Bielefeld würde das zu weit gehen.
