### ISSUE TITLE
Fragen zu Datensätzen

### ISSUE THREAD

**Issue by Duragtan** [stadt-bielefeld/izud#13]
Verschiedene der Wissenschaftler\*innen mit denen ich gesprochen habe, wiesen auf die Notwendigkeit Nachfragen zu einem Datensatz stellen zu können hin. Ideal wäre aus ihrer Sicht, wenn es eine Möglichkeit gäbe eine Fragen an d\*ie Datensatzautor\*in zu stellen und wenn die Frage geklärt wurde Frage und Antwort in die öffentliche Dokumentation des Datensatzes aufgenommen würden.

**Comment by buprak** [comment]
Auf unserem Open Data Portal der Stadt Bielefeld versuchen wir zu den Datensätzen entsprechend unter den Metadaten auch fachliche Ansprechpartner*innen zu hinterlegen, sodass jederzeit Nachfragen direkt an die zuständige Person gestellt werden können. Hier geht es zum Portal: https://open-data.bielefeld.de/
