### ISSUE TITLE
Einheitliche Termini

### ISSUE THREAD

**Issue by Duragtan** [stadt-bielefeld/izud#15]
Unter Abschnitt "4. Datenhoheit" sprechen wir gleich im ersten Satz von der "Verwaltung" von Daten. Warum hier nicht auch wieder von Datenhoheit? Wir sollten solche generell vermeiden verschiedene Termini zu verwenden, die in eine ähnlich Richtung gehe, aber in einem unklaren Zusammenhang zu einander stehen. Bsp. "Datenhoheit" <-> "Verwaltung von Daten".

**Comment by buprak** [comment]
Die Rückmeldungen wurden in der Überarbeitung entsprechend übernommen und können in der neuen Version nachgelesen werden.
