### ISSUE TITLE
Digital ist nicht notwendigerweise auswertbar

### ISSUE THREAD

**Issue by Duragtan** [stadt-bielefeld/izud#6]
Ein Punkt auf den einer unserer Forschenden abhob, war die Maschinen-Lesbarkeit von Daten. Eine pdf-Datei die Tabellen mit Daten beinhaltet stellt zwar technisch einen digitalen Datensatz dar. Aber man kann ihn nur mit sehr großem Aufwand in eine Form überführen mit der man die Daten darin auch auswerten kann. 

Der Wunsch des Forschenden war, dass Daten a.) in eine leicht auswertbaren Form veröffentlicht werden sollen und b.) dass man sich ggf. an existierenden Standards für Meta-Daten orientiert.

**Comment by buprak** [comment]
Diese Überlegung haben wir derzeit auch intern und berücksichtigen diese bei internen Prozessen zur Veröffentlichung von Verwaltungsdaten. Zu überlegen wäre sowas auch öffentlich aufzubereiten als eine Art Leitfaden.

Dazu können wir gerne nochmal sprechen! Für unseren Entwurf zum Umgang mit Daten in der Stadt Bielefeld würde das zu weit gehen.
