### ISSUE TITLE
Mehrwerte für die Stadt-Verwaltung

### ISSUE THREAD

**Issue by Duragtan** [stadt-bielefeld/izud#8]
Ein wichtiger Bereitsteller von Daten wird voraussichtlich die Verwaltung der Stadt Bielefeld sein. Einer unserer Forschenden hat die Idee aufgeworfen, die Vorteile, die die Stadtverwaltung aus dem Bereitstellen der Daten haben könnte stärker herauszustellen und auch mitzudenken.

Insbesondere könnte man einen Kanal schaffen, durch Dinge, die mit den Daten gemacht werden wieder zurück an die Stadt fließen können. Das könnte ganz einfach sein, in dem man unter jeden Datensatz schreibt 

> Bitte senden Sie uns Informationen dazu wie Sie diese Daten nutzen (Link, Dokument, Excel-Datei, Jupyter-Notebook, ...) an digitalsein@bielefeld.de

Oder auch deutlich aufwändiger wie eine DKAN-Platform oder eine Plattform für "datenbasierten Bürgerdialog" (was immer das dann im Detail heißen würde).

**Comment by buprak** [comment]
Die Rückmeldung haben wir entsprechend in der Überarbeitung des Entwurfs mitaufgenommen.
