### ISSUE TITLE
Veröffentlichung von Daten keine binäre Entscheidung

### ISSUE THREAD

**Issue by Duragtan** [stadt-bielefeld/izud#9]
Es gibt bei der Frage, ob ein gegebener Datensatz veröffentlicht werden soll mehr als die Antworten "ja"/"nein". Denkbar wäre bei Daten mit Missbrauchspotential (Beispiel aus dem InnoZ UB Brutstandort Wiedehopf)  z.B. eine Veröffentlichung entsprechen agregierter Daten (Anzahl brütender Paare statt Neststandorte) oder eine Herausgabe nur auf Anfrage und an Personen deren Identität festgestellt wurde.

**Comment by buprak** [comment]
Die Rückmeldung haben wir entsprechend in der Überarbeitung berücksichtigt.
